name: Scorecard supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: '18 23 * * 0,2,4'   # 每週日、二、四執行
  push:
    branches: [ "main" ]

permissions: read-all

jobs:
  analysis:
    runs-on: ubuntu-latest
    if: github.event.repository.default_branch == github.ref_name || github.event_name == 'pull_request'
    permissions:
      security-events: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
